training_pipeline_config:
  pipeline_name: us_visa
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/Shivan118/Main-Branching/main/Visadataset.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  schema_dir: config
  schema_file_path: schema.yaml


data_transformation_config :
   transformed_dir : transformed_data
   transformed_train_dir : train
   transformed_test_dir : test
   preprocessing_dir : preprocessed
   preprocessed_object_file_path : preprocessed.pkl
   
